### ISSUE TITLE
[Question] Does this boot selector support both internal/external drives active when swapped?

### ISSUE THREAD

**Issue by ceztko** [OlegMishin/A500_BootSel#1]
1) Can you use both drives when the external floppy is DF0 using this board?
2) Is this board same/similar as the one sold [here](https://sordan.ie/product/1165/switchless-boot-selector-amiga-500-df0df1-signal-sel0-from-sel1/)?
2) Do you also support soft swap with press and hold the reset keys for few seconds? Board above does it (but doesn't have the physical jumper).

**Comment by OlegMishin** [comment]
1. Yes, it is possible. The board does a swap between DF0-DF1. If external drive is DF0, internal one is DF1.
2. It is similar. The main difference is the MCU. I use ATtiny in soic-8 package. 
3. First of all, there are two configurations. The first is "hardware" or "Switch" mode, using a switch as shown in the main page. The second is "Software" mode using the MCU. In this configuration you can control the swap with long RESET. I will upload both schematics in short.

I found the "Software" mode not so convenient, so ended up with the "Switch" configuration.

**Comment by ceztko** [comment]
> 1. Yes, it is possible. The board does a swap between DF0-DF1. If external drive is DF0, internal one is DF1.

Wow, the one on Sordan store says it's not possible to use internal drive once swapped, and they say this is common for boot selectors to behave like this.

> 3. First of all, there are two configurations. The first is "hardware" or "Switch" mode, using a switch as shown in the main page. The second is "Software" mode using the MCU. In this configuration you can control the swap with long RESET. I will upload both schematics in short.
> 

Maybe it would be even more flexible to have both circuits available? I mean, the switch would decide the default, but the software control would still be available to switch it, if one needs it from time to time.

Again, it would be great to find this product in a store, especially if it really allows to use both drives with external as DF0 and internal as DF1.

**Comment by OlegMishin** [comment]
I think, the other project works the same way as mine. Basically, both circuits are very similar. Most likely in the other project's description real meaning is that the internal floppy is not bootable when swapped (it is DF1 then). This is not fully true as KS2.x and higher supports boot from DF1. But some games do not work from DF1.
At the bottomline, both projects just swap DF0 - DF1. You can copy files in both directions, doesn't matter either the floppies are swapped or not.

Regarding flexibility with MCU and switch, lets see if I have time. The projects I share are hobby ones and targeted to hobbiest who can build them by them by themselves or use as a starting point for their own project. 
Since I have a full-time job (sometimes evene more than full-time :) ) I do not consider  any mass-production. It is a big difference between hobby device and mass-production one in terms of effords needed.

Regards
Oleg

**Comment by ceztko** [comment]
> Most likely in the other project's description real meaning is that the internal floppy is not bootable when swapped

I did a small research on what's available in the marked. Switchless swappers that state that the internal drive is disabled: 1) [link]( https://www.amigakit.com/switchless-floppy-drive-boot-selector-a500-a2000-p-91294.html?aksid=ohmqe60rsvlkeab82r91gnd0bf&currency=GBP&aksid=ohmqe60rsvlkeab82r91gnd0bf), 2) [link](https://www.gotek-retro.eu/switchless-boot-selector/), 3) [link](https://sordan.ie/product/1165/switchless-boot-selector-amiga-500-df0df1-signal-sel0-from-sel1/) . Switchless swappers that state the internal drive is not disabled: 1) [link](https://www.tinkerboy.xyz/product/tinkerboy-amiga-drive-selector-switchless-boot-selector-for-amiga/) , 2) your.

Sadly I already bought one that mention that the internal drive is disabled so I can give you feedback later on the accuracy of this specification. Both physical and soft switches available would be interesting to have since people probably prefer to have the external Gotek as DF0 and rarely swap the order with soft switch.  I couldn't find any product/open source project that has this feature.

**Comment by OlegMishin** [comment]
Ok, clear. Thanks for the research :) Honestly, I have never considered to disable internal floppy as it is very easy to swap the drives. If you have a look at its schematict, it is straight forward.
I didn't want to reinven a wheel, but seems such double functionality would be a new feature. I will try to find time to update the project.

One of reasons why I not proceed with this priject is that I developed a keyboard controller for A500 which has functionality to switch kickstart and Floppy via SHIFT-CTRL-AMIGA combination and just use my boot selector as a "Switch" version controlled by the keyboard controller. Maybe I will share the project later. It has a QFN MCU which is difficult to solder. I used it as I had it in my hands.

I mean this one:

![image](https://github.com/OlegMishin/A500_BootSel/assets/81614352/0e4ea9e5-3f55-4de8-b56c-05267a7657b9)

**Comment by ceztko** [comment]
If you make an evolution with the double functionality I would be happy to buy a sample from you and test it together kickstart 3.2 (if it can actually make a difference).

**Comment by OlegMishin** [comment]
Hi @ceztko, 
based on our discussion I made another version of the BootSelector - revision 3. Please have look at the main project's page.
Couple of samples are available for testing.
Regards
Oleg

**Comment by ceztko** [comment]
Hello, sorry for the late answer: I'm interested, how can I contact you privately? Maybe I search for your email address in the commits of your projects?

**Comment by OlegMishin** [comment]
Hi, you can contact me via LinkedIn: https://www.linkedin.com/in/omishin/  or via email: first name, underscore, last name @ yahoo.com
